batman-adv-y += ../../compat-sources/net/core/skbuff.o
batman-adv-y += ../../compat-sources/net/ipv4/igmp.o
batman-adv-y += ../../compat-sources/net/ipv6/mcast_snoop.o
batman-adv-y += ../../compat-sources/net/bridge/br_multicast.o
